---
- name: Install MariaDB server and client
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
    state: present
  become: yes

- name: Start and enable MariaDB service
  systemd:
    name: mariadb
    state: started
    enabled: yes
  become: yes
  notify: restart mariadb

- name: Set MariaDB root password
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  become: yes

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
  notify: restart mariadb
